version: '3.8'

services:
    web:
        build: .
        container_name: laravel_app
        ports:
            - "9000:80"
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        ports:
            - "3333:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
